---

name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - master
      - '[0-9].[0-9]'
      - '[0-9].x'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'
      - '[0-9].x'
  schedule:
    - cron: '0 1 * * *' # nightly build

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: System setup
        run: |
          sudo apt update
          sudo apt install -y stunnel make
          make system-setup
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Build docs
        run: |
          mvn javadoc:jar
      - name: Run tests
        run: |
          TEST="" make test
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: sleep 10s
        run: sleep 10s
      - name: Make - start
        run: |
          make start
          sleep 2s
      - name: Docker - mod or stack
        run: docker run -p 52567:6379 -d redis/redis-stack-server:edge
      - name: Test commands - default protocol
        run: mvn -Dtest="redis.clients.jedis.commands.**" test
      - name: Test commands - RESP3 protocol
        run: mvn -DjedisProtocol=3 -Dtest="redis.clients.jedis.commands.**" test
      - name: Test module commands - default protocol
        run: mvn -DmodulesDocker="localhost:52567" -Dtest="redis.clients.jedis.modules.**" test
      - name: Test module commands - RESP3 protocol
        run: mvn -DjedisProtocol=3 -DmodulesDocker="localhost:52567" -Dtest="redis.clients.jedis.modules.**" test
      - name: Make - stop
        run: make stop
      - name: Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
